
try { example.core.init(); } catch (e) { console.error("An error occurred when calling (example.core/init)"); throw(e); }